export const GET_PRODUCT_TYPES = 'admin/App/GET_PRODUCT_TYPES';
export const GET_PRODUCT_TYPES_SUCCESS = 'admin/App/GET_PRODUCT_TYPES_SUCCESS';
export const GET_PRODUCT_TYPES_ERROR = 'admin/App/GET_PRODUCT_TYPES_ERROR';

export const DELETE_PRODUCT_TYPE = 'admin/App/DELETE_PRODUCT_TYPE';
export const DELETE_PRODUCT_TYPE_SUCCESS = 'admin/App/DELETE_PRODUCT_TYPE_SUCCESS';
export const DELETE_PRODUCT_TYPE_ERROR = 'admin/App/DELETE_PRODUCT_TYPE_ERROR';

export const UPDATE_PRODUCT_TYPES = 'admin/App/UPDATE_PRODUCT_TYPES';