export const ADD_PROGRAM_WEEKLY = 'admin/App/ADD_PROGRAM_WEEKLY';
export const ADD_PROGRAM_WEEKLY_SUCCESS = 'admin/App/ADD_PROGRAM_WEEKLY_SUCCESS';
export const ADD_PROGRAM_WEEKLY_ERROR = 'admin/App//ADD_PROGRAM_WEEKLY_ERROR';