export const GET_PROGRAM_WEEKLIES = 'admin/App/GET_PROGRAM_WEEKLIES';
export const GET_PROGRAM_WEEKLIES_SUCCESS = 'admin/App/GET_PROGRAM_WEEKLIES_SUCCESS';
export const GET_PROGRAM_WEEKLIES_ERROR = 'admin/App/GET_PROGRAM_WEEKLIES_ERROR';

export const DELETE_PROGRAM_WEEKLY = 'admin/App/DELETE_PROGRAM_WEEKLY';
export const DELETE_PROGRAM_WEEKLY_SUCCESS = 'admin/App/DELETE_PROGRAM_WEEKLY_SUCCESS';
export const DELETE_PROGRAM_WEEKLY_ERROR = 'admin/App/DELETE_PROGRAM_WEEKLY_ERROR';

export const FILTER_PROGRAM_WEEKLIES = 'admin/App/FILTER_PROGRAM_WEEKLIES';
