export const UPDATE_MACHINE = 'admin/App/UPDATE_MACHINE';
export const UPDATE_MACHINE_SUCCESS = 'admin/App/UPDATE_MACHINE_SUCCESS';
export const UPDATE_MACHINE_ERROR = 'admin/App/UPDATE_MACHINE_ERROR';