export const UPDATE_MACHINE = 'admin/App/UPDATE_MACHINE';
export const UPDATE_MACHINE_SUCCESS = 'admin/App/UPDATE_MACHINE_SUCCESS';
export const UPDATE_MACHINE_ERROR = 'admin/App/UPDATE_MACHINE_ERROR';

export const EDIT_GET_MACHINES = 'admin/App/EDIT_GET_MACHINES';
export const EDIT_GET_MACHINES_SUCCESS = 'admin/App/EDIT_GET_MACHINES_SUCCESS';
export const EDIT_GET_MACHINES_ERROR = 'admin/App/EDIT_GET_MACHINES_ERROR';