export const UPDATE_CLIENT = 'admin/App/UPDATE_CLIENT';
export const UPDATE_CLIENT_SUCCESS = 'admin/App/UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_ERROR = 'admin/App/UPDATE_CLIENT_ERROR';

export const GET_AVAILABLE_MACHINES = 'admin/App/GET_AVAILABLE_MACHINES';
export const GET_AVAILABLE_MACHINES_SUCCESS = 'admin/App/GET_AVAILABLE_MACHINES_SUCCESS';
export const GET_AVAILABLE_MACHINES_ERROR = 'admin/App/GET_AVAILABLE_MACHINES_ERROR';

export const GET_CLIENT = 'admin/App/GET_CLIENT';
export const GET_CLIENT_SUCCESS = 'admin/App/GET_CLIENT_SUCCESS';
export const GET_CLIENT_ERROR = 'admin/App/GET_CLIENT_ERROR';
