export const UPDATE_RAVITAILLEUR = 'admin/App/UPDATE_RAVITAILLEUR';
export const UPDATE_RAVITAILLEUR_SUCCESS = 'admin/App/UPDATE_RAVITAILLEUR_SUCCESS';
export const UPDATE_RAVITAILLEUR_ERROR = 'admin/App/UPDATE_RAVITAILLEUR_ERROR';