export const UPDATE_RAVITAILLEUR = 'admin/App/UPDATE_RAVITAILLEUR';
export const UPDATE_RAVITAILLEUR_SUCCESS = 'admin/App/UPDATE_RAVITAILLEUR_SUCCESS';
export const UPDATE_RAVITAILLEUR_ERROR = 'admin/App/UPDATE_RAVITAILLEUR_ERROR';
export const GET_RAVITAILLEUR = 'admin/App/GET_RAVITAILLEUR';
export const GET_RAVITAILLEUR_SUCCESS = 'admin/App/GET_RAVITAILLEUR_SUCCESS';
export const GET_RAVITAILLEUR_ERROR = 'admin/App/GET_RAVITAILLEUR_ERROR';