export const GET_PROGRAMME_LIST = 'admin/App/GET_PROGRAMME_LIST';
export const GET_PROGRAMME_LIST_SUCCESS = 'admin/App/GET_PROGRAMME_LIST_SUCCESS';
export const GET_PROGRAMME_LIST_ERROR = 'admin/App/GET_PROGRAMME_LIST_ERROR';