export const ADD_RAVITAILLEUR = 'admin/App/ADD_RAVITAILLEUR';
export const ADD_RAVITAILLEUR_SUCCESS = 'admin/App/ADD_RAVITAILLEUR_SUCCESS';
export const ADD_RAVITAILLEUR_ERROR = 'admin/App//ADD_RAVITAILLEUR_ERROR';