export const GET_RAVITAILLEURS = 'admin/App/GET_RAVITAILLEURS';
export const GET_RAVITAILLEURS_SUCCESS = 'admin/App/GET_RAVITAILLEURS_SUCCESS';
export const GET_RAVITAILLEURS_ERROR = 'admin/App/GET_RAVITAILLEURS_ERROR';

export const DELETE_RAVITAILLEUR = 'admin/App/DELETE_RAVITAILLEUR';
export const DELETE_RAVITAILLEUR_SUCCESS = 'admin/App/DELETE_RAVITAILLEUR_SUCCESS';
export const DELETE_RAVITAILLEUR_ERROR = 'admin/App/DELETE_RAVITAILLEUR_ERROR';

export const UPDATE_RAVITAILLEURS = 'admin/App/UPDATE_RAVITAILLEURS';