export const ADD_PRODUCT = 'admin/App/ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'admin/App/ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'admin/App/ADD_PRODUCT_ERROR';

export const ADD_GET_PRODUCT_TYPES = 'admin/App/ADD_GET_PRODUCT_TYPES';
export const ADD_GET_PRODUCT_TYPES_SUCCESS = 'admin/App/ADD_GET_PRODUCT_TYPES_SUCCESS';
export const ADD_GET_PRODUCT_TYPES_ERROR = 'admin/App/ADD_GET_PRODUCT_TYPES_ERROR';