export const ADD_CLIENT = 'admin/App/ADD_CLIENT';
export const ADD_CLIENT_SUCCESS = 'admin/App/ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_ERROR = 'admin/App/ADD_CLIENT_ERROR';

export const GET_AVAILABLE_MACHINES = 'admin/App/GET_AVAILABLE_MACHINES';
export const GET_AVAILABLE_MACHINES_SUCCESS = 'admin/App/GET_AVAILABLE_MACHINES_SUCCESS';
export const GET_AVAILABLE_MACHINES_ERROR = 'admin/App/GET_AVAILABLE_MACHINES_ERROR';