export const GET_MACHINES = 'admin/App/GET_MACHINES';
export const GET_MACHINES_SUCCESS = 'admin/App/GET_MACHINES_SUCCESS';
export const GET_MACHINES_ERROR = 'admin/App/GET_MACHINES_ERROR';

export const DELETE_MACHINE = 'admin/App/DELETE_MACHINE';
export const DELETE_MACHINE_SUCCESS = 'admin/App/DELETE_MACHINE_SUCCESS';
export const DELETE_MACHINE_ERROR = 'admin/App/DELETE_MACHINE_ERROR';
