export const GET_PRODUCT_TYPE = 'admin/App/GET_PRODUCT_TYPE';
export const GET_PRODUCT_TYPE_SUCCESS = 'admin/App/GET_PRODUCT_TYPE_SUCCESS';
export const GET_PRODUCT_TYPE_ERROR = 'admin/App/GET_PRODUCT_TYPE_ERROR';
export const UPDATE_PRODUCT_TYPE = 'admin/App/UPDATE_PRODUCT_TYPE';
export const UPDATE_PRODUCT_TYPE_SUCCESS = 'admin/App/UPDATE_PRODUCT_TYPE_SUCCESS';
export const UPDATE_PRODUCT_TYPE_ERROR = 'admin/App/UPDATE_PRODUCT_TYPE_ERROR';