export const UPDATE_PROGRAM_WEEKLY = 'admin/App/UPDATE_PROGRAM_WEEKLY';
export const UPDATE_PROGRAM_WEEKLY_SUCCESS = 'admin/App/UPDATE_PROGRAM_WEEKLY_SUCCESS';
export const UPDATE_PROGRAM_WEEKLY_ERROR = 'admin/App//UPDATE_PROGRAM_WEEKLY_ERROR';

export const GET_AVAILABLE_CLIENTS = 'admin/App/GET_AVAILABLE_CLIENTS';
export const GET_AVAILABLE_CLIENTS_SUCCESS = 'admin/App/GET_AVAILABLE_CLIENTS_SUCCESS';
export const GET_AVAILABLE_CLIENTS_ERROR = 'admin/App/GET_AVAILABLE_CLIENTS_ERROR';

export const GET_AVAILABLE_RAVITAILLEURS = 'admin/App/GET_AVAILABLE_RAVITAILLEURS';
export const GET_AVAILABLE_RAVITAILLEURS_SUCCESS = 'admin/App/GET_AVAILABLE_RAVITAILLEURS_SUCCESS';
export const GET_AVAILABLE_RAVITAILLEURS_ERROR = 'admin/App/GET_AVAILABLE_RAVITAILLEURS_ERROR';

export const GET_PROGRAM_WEEKLY = 'admin/App/GET_PROGRAM_WEEKLY';
export const GET_PROGRAM_WEEKLY_SUCCESS = 'admin/App/GET_PROGRAM_WEEKLY_SUCCESS';
export const GET_PROGRAM_WEEKLY_ERROR = 'admin/App/GET_PROGRAM_WEEKLY_ERROR';