export const GET_PRODUCT = 'admin/App/GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'admin/App/GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'admin/App/GET_PRODUCT_ERROR';
export const UPDATE_PRODUCT = 'admin/App/UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'admin/App/UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'admin/App/UPDATE_PRODUCT_ERROR';

export const EDIT_GET_PRODUCT_TYPES = 'admin/App/EDIT_GET_PRODUCT_TYPES';
export const EDIT_GET_PRODUCT_TYPES_SUCCESS = 'admin/App/EDIT_GET_PRODUCT_TYPES_SUCCESS';
export const EDIT_GET_PRODUCT_TYPES_ERROR = 'admin/App/EDIT_GET_PRODUCT_TYPES_ERROR';